---
collections:
  - name: community.general
    version: "7.0.1"
  - name: ansible.windows
    version: "1.14.0"
  - name: ansible.posix
    version: "1.5.4"
  - name: community.windows
    version: "1.13.0"
  - name: kubernetes.core
    version: "2.4.0"
  - name: community.crypto
    version: "2.13.1"
  - name: community.mysql
    version: "3.7.1"
  - name: openstack.cloud
    version: "2.1.0"
  - name: community.postgresql
    version: "2.4.1"
  - name: community.docker
    version: "3.12.1"
  - name: "ansible.netcommon"
    version: "5.1.1"
  - name: "google.cloud"
    version: "1.1.3"
  - name: "chocolatey.chocolatey"
    version: "1.4.0"
