apiVersion: apps/v1
kind: Deployment
metadata:
  name: concord-agent-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: concord-agent-operator
  template:
    metadata:
      labels:
        name: concord-agent-operator
    spec:
      serviceAccountName: concord-agent-operator
      containers:
        - name: concord-agent-operator
          image: "walmartlabs/concord-agent-operator:latest"
          imagePullPolicy: Never
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "concord-agent-operator"
            - name: CONCORD_BASE_URL
              value: "http://192.168.0.157:8001" # replace with local IP
            - name: CONCORD_API_TOKEN
              value: "...token..."
