# Custom build flow to publish concord-base, concord-server and concord-agent multi-arch images using JDK17

name: build-jdk17-images

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: Release tag

concurrency:
  group: ${{ github.ref }}-build-jdk17-images
  cancel-in-progress: true

env:
  DOCKER_REGISTRY: "ibodrov"

jobs:
  build-jdk17-images:
    runs-on: ubuntu-latest

    steps:
      - name: Clear old Docker resources
        run: |
          docker rm -f $(docker ps -aq) || true
          docker system prune -af || true
          docker image prune -f || true
          docker volume prune -f || true

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download release artifacts
        run: ./mvnw -C -B -f docker-images clean install -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.OSS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.OSS_DOCKERHUB_PASSWORD }}

      - name: Build and push the base image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./docker-images/base
          file: ./docker-images/base/oss/centos/Dockerfile
          platforms: linux/amd64, linux/aarch64
          build-args: |
            jdk_url=https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.3%2B7/OpenJDK17U-jdk_aarch64_linux_hotspot_17.0.3_7.tar.gz
          tags: |
            ${{ env.DOCKER_REGISTRY }}/concord-base:${{ github.event.inputs.tag }}-jdk17
            ${{ env.DOCKER_REGISTRY }}/concord-base:latest-jdk17

      - name: Build and push the server image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./docker-images/server
          file: ./docker-images/server/oss/Dockerfile
          platforms: linux/amd64, linux/aarch64
          build-args: |
            docker_namespace=${{ env.DOCKER_REGISTRY }}
            concord_version=${{ github.event.inputs.tag }}-jdk17
            jdk_url=https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.3%2B7/OpenJDK17U-jdk_aarch64_linux_hotspot_17.0.3_7.tar.gz
          tags: |
            ${{ env.DOCKER_REGISTRY }}/concord-server:${{ github.event.inputs.tag }}-jdk17
            ${{ env.DOCKER_REGISTRY }}/concord-server:latest-jdk17

      - name: Build and push the ansible image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./docker-images/ansible
          file: ./docker-images/ansible/oss/centos/Dockerfile
          platforms: linux/amd64, linux/aarch64
          build-args: |
            docker_namespace=${{ env.DOCKER_REGISTRY }}
            concord_version=${{ github.event.inputs.tag }}-jdk17
          tags: |
            ${{ env.DOCKER_REGISTRY }}/concord-ansible:${{ github.event.inputs.tag }}-jdk17
            ${{ env.DOCKER_REGISTRY }}/concord-ansible:latest-jdk17

      - name: Build and push the agent image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./docker-images/agent
          file: ./docker-images/agent/oss/centos/Dockerfile
          platforms: linux/amd64, linux/aarch64
          build-args: |
            docker_namespace=${{ env.DOCKER_REGISTRY }}
            concord_version=${{ github.event.inputs.tag }}-jdk17
          tags: |
            ${{ env.DOCKER_REGISTRY }}/concord-agent:${{ github.event.inputs.tag }}-jdk17
            ${{ env.DOCKER_REGISTRY }}/concord-agent:latest-jdk17
